apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: quay.io/theothertom/kubernetes-kibana:20c8dd7e
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_HOST
          value: elasticsearch-logging
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: monitoring
spec:
  rules:
  - host: kibana.monitoring.apps.poc-cluster.ngn-dev.ntch.co.uk
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    protocol: TCP
